version: '3'

services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vault
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - vault-network

  vault:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vault
    environment:
      - VAULT_SECRET=secret
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/vault?sslmode=disable
      - GITHUB_CLIENT_ID=af0cc6a58498de1f11b6
    ports:
      - "1203:1203"
    networks:
      - vault-network
    depends_on:
      - postgres

networks:
  vault-network:
    driver: bridge

